from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.book import Book
from openapi_server.models.cursor_pagination import CursorPagination
from openapi_server import util

from openapi_server.models.book import Book  # noqa: E501
from openapi_server.models.cursor_pagination import CursorPagination  # noqa: E501

class ApiV1BooksGet200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, books=None, pagination=None):  # noqa: E501
        """ApiV1BooksGet200ResponseData - a model defined in OpenAPI

        :param books: The books of this ApiV1BooksGet200ResponseData.  # noqa: E501
        :type books: List[Book]
        :param pagination: The pagination of this ApiV1BooksGet200ResponseData.  # noqa: E501
        :type pagination: CursorPagination
        """
        self.openapi_types = {
            'books': List[Book],
            'pagination': CursorPagination
        }

        self.attribute_map = {
            'books': 'books',
            'pagination': 'pagination'
        }

        self._books = books
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'ApiV1BooksGet200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _api_v1_books_get_200_response_data of this ApiV1BooksGet200ResponseData.  # noqa: E501
        :rtype: ApiV1BooksGet200ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def books(self) -> List[Book]:
        """Gets the books of this ApiV1BooksGet200ResponseData.


        :return: The books of this ApiV1BooksGet200ResponseData.
        :rtype: List[Book]
        """
        return self._books

    @books.setter
    def books(self, books: List[Book]):
        """Sets the books of this ApiV1BooksGet200ResponseData.


        :param books: The books of this ApiV1BooksGet200ResponseData.
        :type books: List[Book]
        """

        self._books = books

    @property
    def pagination(self) -> CursorPagination:
        """Gets the pagination of this ApiV1BooksGet200ResponseData.


        :return: The pagination of this ApiV1BooksGet200ResponseData.
        :rtype: CursorPagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: CursorPagination):
        """Sets the pagination of this ApiV1BooksGet200ResponseData.


        :param pagination: The pagination of this ApiV1BooksGet200ResponseData.
        :type pagination: CursorPagination
        """

        self._pagination = pagination
