### ========== USER API ==========

### GET all users
GET http://localhost:5001/api/v1/users
Accept: application/json

###

### GET single user
GET http://localhost:5001/api/v1/users/1
Accept: application/json

###

### POST create user
POST http://localhost:5001/api/v1/users
Accept: application/json
Content-Type: application/json

{
  "name": "Student",
  "email": "student1@uet.vnu.edu.vn"
}

###

### GET user borrows
GET http://localhost:5001/api/v1/users/1/borrows
Accept: application/json



### ========== BOOK API TEST ==========

### GET all books
GET http://localhost:5001/api/v1/books
Accept: application/json

###

### GET only available books
GET http://localhost:5001/api/v1/books?available=true
Accept: application/json

###

### GET single book
GET http://localhost:5001/api/v1/books/2
Accept: application/json

###

### CREATE new book
POST http://localhost:5001/api/v1/books
Accept: application/json
Content-Type: application/json

{
  "title": "Flask for Beginners 2",
  "author": "Cuong Dung"
}

###

### UPDATE book (full update with PUT)
PUT http://localhost:5001/api/v1/books/1
Accept: application/json
Content-Type: application/json

{
  "title": "Flask Advanced",
  "author": "Nguyen Van B",
  "available": false
}

###

### DELETE book
DELETE http://localhost:5001/api/v1/books/1
Accept: application/json

### Borrow a book
POST http://localhost:5001/api/v1/books/2/borrow
Accept: application/json

###

### Return a book
POST http://localhost:5001/api/v1/books/2/return
Accept: application/json
