# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x07\n\x05\x45mpty\"\x1b\n\rUserIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"<\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"9\n\x0cUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\rUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9e\x02\n\x0bUserService\x12\x32\n\x07GetUser\x12\x13.user.UserIdRequest\x1a\x12.user.UserResponse\x12,\n\x08GetUsers\x12\x0b.user.Empty\x1a\x13.user.UsersResponse\x12\x39\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\x12\x39\n\nUpdateUser\x12\x17.user.UpdateUserRequest\x1a\x12.user.UserResponse\x12\x37\n\nDeleteUser\x12\x13.user.UserIdRequest\x1a\x14.user.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_USERIDREQUEST']._serialized_start=29
  _globals['_USERIDREQUEST']._serialized_end=56
  _globals['_CREATEUSERREQUEST']._serialized_start=58
  _globals['_CREATEUSERREQUEST']._serialized_end=106
  _globals['_UPDATEUSERREQUEST']._serialized_start=108
  _globals['_UPDATEUSERREQUEST']._serialized_end=168
  _globals['_USER']._serialized_start=170
  _globals['_USER']._serialized_end=217
  _globals['_USERRESPONSE']._serialized_start=219
  _globals['_USERRESPONSE']._serialized_end=276
  _globals['_USERSRESPONSE']._serialized_start=278
  _globals['_USERSRESPONSE']._serialized_end=320
  _globals['_DELETERESPONSE']._serialized_start=322
  _globals['_DELETERESPONSE']._serialized_end=372
  _globals['_USERSERVICE']._serialized_start=375
  _globals['_USERSERVICE']._serialized_end=661
# @@protoc_insertion_point(module_scope)
