from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.api_v1_members_get200_response_data import ApiV1MembersGet200ResponseData
from openapi_server import util

from openapi_server.models.api_v1_members_get200_response_data import ApiV1MembersGet200ResponseData  # noqa: E501

class ApiV1MembersGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """ApiV1MembersGet200Response - a model defined in OpenAPI

        :param data: The data of this ApiV1MembersGet200Response.  # noqa: E501
        :type data: ApiV1MembersGet200ResponseData
        """
        self.openapi_types = {
            'data': ApiV1MembersGet200ResponseData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ApiV1MembersGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _api_v1_members_get_200_response of this ApiV1MembersGet200Response.  # noqa: E501
        :rtype: ApiV1MembersGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> ApiV1MembersGet200ResponseData:
        """Gets the data of this ApiV1MembersGet200Response.


        :return: The data of this ApiV1MembersGet200Response.
        :rtype: ApiV1MembersGet200ResponseData
        """
        return self._data

    @data.setter
    def data(self, data: ApiV1MembersGet200ResponseData):
        """Sets the data of this ApiV1MembersGet200Response.


        :param data: The data of this ApiV1MembersGet200Response.
        :type data: ApiV1MembersGet200ResponseData
        """

        self._data = data
