from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.book_borrowed import BookBorrowed
from openapi_server.models.cursor_pagination import CursorPagination
from openapi_server import util

from openapi_server.models.book_borrowed import BookBorrowed  # noqa: E501
from openapi_server.models.cursor_pagination import CursorPagination  # noqa: E501

class ApiV1BooksBorrowedGet200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, books_borrowed=None, pagination=None):  # noqa: E501
        """ApiV1BooksBorrowedGet200ResponseData - a model defined in OpenAPI

        :param books_borrowed: The books_borrowed of this ApiV1BooksBorrowedGet200ResponseData.  # noqa: E501
        :type books_borrowed: List[BookBorrowed]
        :param pagination: The pagination of this ApiV1BooksBorrowedGet200ResponseData.  # noqa: E501
        :type pagination: CursorPagination
        """
        self.openapi_types = {
            'books_borrowed': List[BookBorrowed],
            'pagination': CursorPagination
        }

        self.attribute_map = {
            'books_borrowed': 'books_borrowed',
            'pagination': 'pagination'
        }

        self._books_borrowed = books_borrowed
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'ApiV1BooksBorrowedGet200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _api_v1_books_borrowed_get_200_response_data of this ApiV1BooksBorrowedGet200ResponseData.  # noqa: E501
        :rtype: ApiV1BooksBorrowedGet200ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def books_borrowed(self) -> List[BookBorrowed]:
        """Gets the books_borrowed of this ApiV1BooksBorrowedGet200ResponseData.


        :return: The books_borrowed of this ApiV1BooksBorrowedGet200ResponseData.
        :rtype: List[BookBorrowed]
        """
        return self._books_borrowed

    @books_borrowed.setter
    def books_borrowed(self, books_borrowed: List[BookBorrowed]):
        """Sets the books_borrowed of this ApiV1BooksBorrowedGet200ResponseData.


        :param books_borrowed: The books_borrowed of this ApiV1BooksBorrowedGet200ResponseData.
        :type books_borrowed: List[BookBorrowed]
        """

        self._books_borrowed = books_borrowed

    @property
    def pagination(self) -> CursorPagination:
        """Gets the pagination of this ApiV1BooksBorrowedGet200ResponseData.


        :return: The pagination of this ApiV1BooksBorrowedGet200ResponseData.
        :rtype: CursorPagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: CursorPagination):
        """Sets the pagination of this ApiV1BooksBorrowedGet200ResponseData.


        :param pagination: The pagination of this ApiV1BooksBorrowedGet200ResponseData.
        :type pagination: CursorPagination
        """

        self._pagination = pagination
