from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.cursor_pagination import CursorPagination
from openapi_server.models.member import Member
from openapi_server import util

from openapi_server.models.cursor_pagination import CursorPagination  # noqa: E501
from openapi_server.models.member import Member  # noqa: E501

class ApiV1MembersGet200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, members=None, pagination=None):  # noqa: E501
        """ApiV1MembersGet200ResponseData - a model defined in OpenAPI

        :param members: The members of this ApiV1MembersGet200ResponseData.  # noqa: E501
        :type members: List[Member]
        :param pagination: The pagination of this ApiV1MembersGet200ResponseData.  # noqa: E501
        :type pagination: CursorPagination
        """
        self.openapi_types = {
            'members': List[Member],
            'pagination': CursorPagination
        }

        self.attribute_map = {
            'members': 'members',
            'pagination': 'pagination'
        }

        self._members = members
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'ApiV1MembersGet200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _api_v1_members_get_200_response_data of this ApiV1MembersGet200ResponseData.  # noqa: E501
        :rtype: ApiV1MembersGet200ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def members(self) -> List[Member]:
        """Gets the members of this ApiV1MembersGet200ResponseData.


        :return: The members of this ApiV1MembersGet200ResponseData.
        :rtype: List[Member]
        """
        return self._members

    @members.setter
    def members(self, members: List[Member]):
        """Sets the members of this ApiV1MembersGet200ResponseData.


        :param members: The members of this ApiV1MembersGet200ResponseData.
        :type members: List[Member]
        """

        self._members = members

    @property
    def pagination(self) -> CursorPagination:
        """Gets the pagination of this ApiV1MembersGet200ResponseData.


        :return: The pagination of this ApiV1MembersGet200ResponseData.
        :rtype: CursorPagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: CursorPagination):
        """Sets the pagination of this ApiV1MembersGet200ResponseData.


        :param pagination: The pagination of this ApiV1MembersGet200ResponseData.
        :type pagination: CursorPagination
        """

        self._pagination = pagination
