openapi: 3.0.3
info:
  title: Book Management API
  description: API for managing books in a library system
  version: 1.0.0

servers:
  - url: http://localhost:5001
    description: Local development server

paths:
  /api/v1/books:
    get:
      summary: Get all books
      tags:
        - Books
      parameters:
        - name: available
          in: query
          description: Filter by availability
          required: false
          schema:
            type: boolean
      responses:
        200:
          description: A list of books
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Book"
                  message:
                    type: string
    post:
      summary: Create a new book
      tags:
        - Books
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewBook"
      responses:
        201:
          description: Book created successfully
        400:
          description: Missing required fields

  /api/v1/books/{book_id}:
    get:
      summary: Get a book by ID
      tags:
        - Books
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Book found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
        404:
          description: Book not found
    put:
      summary: Update a book
      tags:
        - Books
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBook"
      responses:
        200:
          description: Book updated successfully
        404:
          description: Book not found
    delete:
      summary: Delete a book
      tags:
        - Books
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Book deleted successfully
        404:
          description: Book not found

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: The Great Gatsby
        author:
          type: string
          example: F. Scott Fitzgerald
        available:
          type: boolean
          example: true

    NewBook:
      type: object
      required:
        - title
        - author
      properties:
        title:
          type: string
          example: Atomic Habits
        author:
          type: string
          example: James Clear

    UpdateBook:
      type: object
      properties:
        title:
          type: string
          example: New Title
        author:
          type: string
          example: New Author
        available:
          type: boolean
          example: false
